version: '3'
services:
  db:
    image: postgres
    container_name: test-dbPostgres
    restart: always
    environment:
      POSTGRES_USER: rjmendezl
      POSTGRES_PASSWORD: WillDomPass
      POSTGRES_DB: WillDomDatabase
    ports:
      - "5432:5432"